# Generated by Django 3.2.9 on 2021-11-27 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_config', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('django_form_class', models.PositiveIntegerField(choices=[(1, 'BooleanField'), (2, 'CharField'), (3, 'ChoiceField'), (4, 'TypedChoiceField'), (5, 'DateField'), (6, 'DateTimeField'), (7, 'DecimalField'), (8, 'DurationField'), (9, 'EmailField'), (10, 'FileField'), (11, 'FilePathField'), (12, 'FloatField'), (13, 'ImageField'), (14, 'IntegerField'), (15, 'JSONField'), (16, 'GenericIPAddressField'), (17, 'MultipleChoiceField'), (18, 'TypedMultipleChoiceField'), (19, 'NullBooleanField'), (20, 'RegexField'), (21, 'SlugField'), (22, 'TimeField'), (23, 'URLField'), (24, 'UUIDField')])),
            ],
        ),
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.fieldtype')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSnapshotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('national', models.CharField(max_length=255)),
                ('world', models.CharField(max_length=255)),
                ('national_letter_designation', models.CharField(max_length=255)),
                ('world_letter_designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reportsnapshotstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reportfield')),
                ('report_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reportsnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='reportfield',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report'),
        ),
        migrations.AddField(
            model_name='reportfield',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.unit'),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='form_field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.formfieldtype'),
        ),
    ]
