# Generated by Django 3.2.9 on 2021-11-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20211127_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtype',
            name='form_field_type',
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='django_form_class',
            field=models.PositiveIntegerField(choices=[(1, 'BooleanField'), (2, 'CharField'), (3, 'ChoiceField'), (4, 'TypedChoiceField'), (5, 'DateField'), (6, 'DateTimeField'), (7, 'DecimalField'), (8, 'DurationField'), (9, 'EmailField'), (10, 'FileField'), (11, 'FilePathField'), (12, 'FloatField'), (13, 'ImageField'), (14, 'IntegerField'), (15, 'JSONField'), (16, 'GenericIPAddressField'), (17, 'MultipleChoiceField'), (18, 'TypedMultipleChoiceField'), (19, 'NullBooleanField'), (20, 'RegexField'), (21, 'SlugField'), (22, 'TimeField'), (23, 'URLField'), (24, 'UUIDField')], default=2),
        ),
        migrations.DeleteModel(
            name='FormFieldType',
        ),
    ]
