# Generated by Django 3.2.9 on 2021-11-28 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('npa', '0001_initial'),
        ('report', '0004_auto_20211127_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfield',
            name='machine_name',
            field=models.SlugField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='npa',
            field=models.ManyToManyField(blank=True, to='npa.NPA'),
        ),
        migrations.AlterField(
            model_name='reportfield',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='report.report'),
        ),
    ]
