# Generated by Django 3.2.9 on 2021-11-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPAType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npa_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('npa_file', models.FileField(blank=True, null=True, upload_to='npa/')),
                ('npa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npa.npatype')),
            ],
        ),
    ]
